apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
  namespace: database
  labels:
    app: backend
spec:
  serviceName: "database"
  replicas: 1
  selector:
    matchLabels:
      app: backend-database
  template:
    metadata:
      labels:
        app: backend-database
      namespace: database
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        args:
          - "--ignore-db-dir=lost+found"
        envFrom:
          - secretRef:
              name: database-secret
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/mysql
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-pvc