apiVersion: v1
kind: Namespace
metadata:
  name: wordpress

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv
  labels:
    storage: local
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/wordpress"
  storageClassName: standard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
  namespace: wordpress
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  storageClassName: standard
  selector:
    matchLabels:
      storage: local