apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deploy
  namespace: wordpress
  labels:
    app: wordpress-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
        version: latest # Para usar no Canary posteriormente
    spec:
      containers:
      - name: wordpress
        image: wordpress:5.8.3-php7.4-apache
        ports:
          - containerPort: 80
            name: wordpress
        volumeMounts:
          - name: wordpress-data
            mountPath: /var/www/html
        resources:
          requests:
            cpu: "0.3"
            memory: 64Mi
          limits:
            cpu: "0.8"
            memory: 128Mi
        env:
          - name: WORDPRESS_DB_HOST
            value: database-service.database.svc.cluster.local
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database-secret
                key: MYSQL_ROOT_PASSWORD
          - name: WORDPRESS_DB_USER
            value: root
          - name: WORDPRESS_DB_NAME
            value: wordpress
      volumes:
        - name: wordpress-data
          persistentVolumeClaim:
            claimName: wordpress-pvc